- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu xenial stable
    update_cache: yes
    state: present
  tags: [docker]

- name: Docker is present
  apt:
    name: docker-ce
    state: latest
    force: yes
  tags: [docker]

- name: Python-pip is present
  apt: name=python-pip state=present
  tags: [docker]

- name: Docker-py is present
  pip: name=docker-py version=1.6.0 state=present
  tags: [docker]

- name: Docker Compose is present
  get_url:
    url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    timeout: 60
  tags: [docker]

- name: Docker Compose permissions are set
  file:
    path: /usr/local/bin/docker-compose
    mode: 0755
  tags: [docker]
